name: Compile Firmware

on: [push]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile application
        id: compile
        uses: particle-iot/compile-action@9dbe1eb567c6268f1baa7458217d5d6e5553850d
        with:
          particle-platform-name: 'bsom'
          #particle-access-token: ${{ secrets.PARTICLE_ACCESS_TOKEN }}
          device-os-version: 6.1.1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: firmware-artifact
          path: ${{ steps.compile.outputs.firmware-path }}
      
      - name: Flash device
        uses: zradlicz/flash-device-action@68019e6b975d230c6d1c8a2fd81f0d162eefab9d8
        with:
          particle-access-token: ${{ secrets.PARTICLE_USER_LEVEL_ACCESS_TOKEN }}
          device-id: ${{ secrets.PARTICLE_TEST_DEVICE_ID }}
          firmware-path: ${{ steps.compile.outputs.firmware-path }}