name: Run Tests

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Create build directory
      run: mkdir -p build
      
    - name: Configure CMake
      run: cd build && cmake ..
      
    - name: Build
      run: cd build && cmake --build .
      
    - name: Find test executable
      run: find build -name "kestrel_tests" -type f -executable
      
    - name: Run tests
      run: |
        TEST_EXECUTABLE=$(find build -name "kestrel_tests" -type f -executable)
        if [ -n "$TEST_EXECUTABLE" ]; then
          $TEST_EXECUTABLE
        else
          echo "Test executable not found!"
          exit 1
        fi